import Head from 'next/head'
import Banner from '../components/Banner'
import MediumCard from '../components/MediumCard'
import Header from '../components/Header'
import SmailCard from '../components/SmailCard'
import LargeCard from '../components/LargeCard'
import LargeCardImg from '../public/LargeCard.webp'
import Footer from '../components/Footer'

export default function Home({ resExploreData, resCardsData }) {
  return (
    <>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://a0.muscache.com/airbnb/static/logotype_favicon-21cc8e6c6a2cca43f061d2dcabdf6e58.ico" />
      </Head>

      <Header />
      <Banner />
      <main className='max-w-7xl px-8 sm:px-16 mx-auto'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>
            Explore Nearby
          </h2>
          <div className=' grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {resExploreData?.map(item =>
              <SmailCard key={item.img} {...item} />
            )}
          </div>
        </section>
        <section>
          <h2 className=' text-4xl font-semibold py-8'>Live Anywehre</h2>
          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3">
            {resCardsData?.map(item =>
              <MediumCard key={item.img} {...item} />
            )}
          </div>
        </section>
          <LargeCard
            img = {LargeCardImg}
            title = "The Greatest Outdoors"
            description = "wishlists curated by Airbnb."
            buttonText = "Get Inspired"
          />
      </main>
      <Footer />
    </>
  )
}


export async function getStaticProps() {
  const exploreData = await fetch('https://links.papareact.com/pyp')
  const resExploreData = await exploreData.json();

  const cardsData = await fetch('https://links.papareact.com/zp1')
  const resCardsData = await cardsData.json();
  return {
    props: {
      resExploreData,
      resCardsData
    }
  }
}